
errtmf           = 1
errfno           = 3
errfnf           = 4
err_missing_fname = 8
err_illegal_device = 9
errnf            = 10
errsn            = 11
errrg            = 12
errod            = 13
errfc            = 14
errov            = 15
errom            = 16
errus            = 17
errbs            = 18
errdd            = 19
errdvo           = 20
errid            = 21
errtm            = 22
errls            = 23
errbd            = 24
errst            = 25
errcn            = 26
erruf            = 27
ervfy            = 28
erload           = 29
erbrk            = 30
errcr            = 31
errlnf           = 32
errlwd           = 33
erroid           = 34
errng            = 35
errbdk           = 36
err_no_bend      = 37
err_too_large    = 38
err_ref          = 39
err_bad_command  = 40
err_file_read    = 41
edit_mode_error  = 42                                     ; [910620]
last_error_message = 42                                     ; # of last error msg

;.end
